server:
  servlet:
    context-path: /booksale
  error:
    whitelabel:
      enable: false

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/booksale
    username: springstudent
    password: springstudent
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookstoregroup174@gmail.com
    password: gbwg pwnz fdbw lvjr
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE